#!/data/data/com.termux/files/usr/bin/bash
# Bamero — generate production .env (Termux / Linux)
# Usage: from project root →  bash setup-env.sh
# After run: edit DOMAIN and SMS only.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT/.env"
EXAMPLE="$ROOT/.env.example"

gen_secret() {
  # 64-char URL-safe-ish secret
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '/+=' | head -c 64
  else
    head -c 64 /dev/urandom | base64 | tr -d '/+=\n' | head -c 64
  fi
}

gen_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '/+=' | head -c 24
  else
    head -c 24 /dev/urandom | base64 | tr -d '/+=\n' | head -c 24
  fi
}

echo "========================================"
echo "  Bamero .env generator"
echo "  Root: $ROOT"
echo "========================================"

if [ -f "$ENV_FILE" ]; then
  BACKUP="$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
  cp "$ENV_FILE" "$BACKUP"
  echo "[!] Existing .env backed up → $BACKUP"
fi

DB_NAME="bamero_db"
DB_USER="bamero_user"
DB_PASSWORD="$(gen_password)"
DB_HOST="localhost"
DB_ROOT_PASSWORD="$(gen_password)"
TABLE_PREFIX="wp_bamero_"

AUTH_KEY="$(gen_secret)"
SECURE_AUTH_KEY="$(gen_secret)"
LOGGED_IN_KEY="$(gen_secret)"
NONCE_KEY="$(gen_secret)"
AUTH_SALT="$(gen_secret)"
SECURE_AUTH_SALT="$(gen_secret)"
LOGGED_IN_SALT="$(gen_secret)"
NONCE_SALT="$(gen_secret)"

# Leave for owner
DOMAIN=""
SMS_API_KEY=""
SMS_API_URL=""
SMS_SENDER=""

cat > "$ENV_FILE" << EOF
# Generated by setup-env.sh — $(date -Iseconds 2>/dev/null || date)
# OWNER: set DOMAIN + SMS_* only, then restart PHP/web server.

# --- Database (auto) ---
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_HOST=${DB_HOST}
DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
TABLE_PREFIX=${TABLE_PREFIX}

# --- WordPress salts (auto — do not share) ---
AUTH_KEY=${AUTH_KEY}
SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
LOGGED_IN_KEY=${LOGGED_IN_KEY}
NONCE_KEY=${NONCE_KEY}
AUTH_SALT=${AUTH_SALT}
SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
LOGGED_IN_SALT=${LOGGED_IN_SALT}
NONCE_SALT=${NONCE_SALT}

# --- Environment ---
WP_ENVIRONMENT_TYPE=production
WP_DEBUG=0
WP_DEBUG_LOG=0
DISALLOW_FILE_MODS=1

# --- OWNER: fill these ---
# Full site URL without trailing slash, e.g. https://rang.chasb.bamero.ir
DOMAIN=${DOMAIN}
# SMS provider (used by your bamero_send_sms filter)
SMS_API_KEY=${SMS_API_KEY}
SMS_API_URL=${SMS_API_URL}
SMS_SENDER=${SMS_SENDER}
EOF

chmod 600 "$ENV_FILE"

# Optional: export helper for current shell
EXPORT_FILE="$ROOT/.env.export.sh"
cat > "$EXPORT_FILE" << 'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# source this file:  source .env.export.sh
set -a
# shellcheck disable=SC1091
. "$(dirname "${BASH_SOURCE[0]:-$0}")/.env"
set +a
echo "Env loaded. DOMAIN still empty? → edit .env"
EOF
chmod 700 "$EXPORT_FILE"

echo ""
echo "[OK] Wrote: $ENV_FILE (mode 600)"
echo ""
echo "Auto-filled:"
echo "  DB_NAME=$DB_NAME"
echo "  DB_USER=$DB_USER"
echo "  DB_PASSWORD=******** (see .env)"
echo "  DB_HOST=$DB_HOST"
echo "  TABLE_PREFIX=$TABLE_PREFIX"
echo "  8× WordPress salts"
echo ""
echo "YOU MUST EDIT .env and set:"
echo "  DOMAIN=https://your-domain.ir"
echo "  SMS_API_KEY=..."
echo "  SMS_API_URL=..."
echo "  SMS_SENDER=..."
echo ""
echo "Next:"
echo "  nano .env"
echo "  # or:  termux-open .env"
echo "  source .env.export.sh"
echo "========================================"
