#!/usr/bin/env bash
#
# Bamero — production bootstrap orchestrator (real, idempotent, fail-closed).
#
# This script contains NO placeholder credentials, NO sample data, NO fake
# contact details and performs NO automatic git operations. Secrets are
# generated by setup-env.sh and read from .env; orchestration is delegated to
# docker compose and wp-cli. Re-running is safe: every step is idempotent.
#
# Usage:
#   bash setup-bamero.sh          # bootstrap a local/staging stack
#   bash setup-bamero.sh --check  # validate prerequisites + .env only (no changes)
#
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

log()  { printf '[bamero] %s\n' "$*"; }
warn() { printf '[bamero][warn] %s\n' "$*" >&2; }
die()  { printf '[bamero][error] %s\n' "$*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required tool: $1"; }

MODE="bootstrap"
[[ "${1:-}" == "--check" ]] && MODE="check"

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
need docker
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (docker compose, not docker-compose)."

# ---------------------------------------------------------------------------
# 2. Environment / secrets (single source of truth = setup-env.sh)
# ---------------------------------------------------------------------------
if [[ ! -f .env ]]; then
    log "no .env found — generating secrets via setup-env.sh"
    [[ "$MODE" == "check" ]] && die ".env is missing; run: bash setup-env.sh"
    bash setup-env.sh
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a

require_env() {
    local key="$1"
    [[ -n "${!key:-}" ]] || die "required value missing in .env: $key"
}

for key in DB_NAME DB_USER DB_PASSWORD DB_HOST DB_ROOT_PASSWORD \
           AUTH_KEY SECURE_AUTH_KEY LOGGED_IN_KEY NONCE_KEY \
           AUTH_SALT SECURE_AUTH_SALT LOGGED_IN_SALT NONCE_SALT; do
    require_env "$key"
done

# Production integrations must be explicitly configured; fail closed otherwise.
[[ -n "${DOMAIN:-}" ]]                 || die "set DOMAIN in .env (e.g. https://rang.example.ir)"
[[ "${SMS_PROVIDER:-}" == "sms_ir" ]]  || die "set SMS_PROVIDER=sms_ir in .env"
require_env SMS_IR_API_KEY
require_env ZARINPAL_MERCHANT_ID
[[ "${ZARINPAL_API_BASE_URL:-}" == https://* ]] || die "ZARINPAL_API_BASE_URL must be https://"

# WordPress core admin account. WordPress core requires an admin e-mail field;
# Bamero keeps it internal-only (never used for customer communication or auth).
WP_ADMIN_USER="${WP_ADMIN_USER:-bamero_admin}"
WP_ADMIN_EMAIL="${WP_ADMIN_EMAIL:-admin@bamero.internal}"
[[ -n "${WP_ADMIN_PASSWORD:-}" ]] || die "set WP_ADMIN_PASSWORD in .env (used once by wp core install)"

log "environment validated (mode: $MODE)"
[[ "$MODE" == "check" ]] && { log "check complete — no changes made."; exit 0; }

# ---------------------------------------------------------------------------
# 3. Start the stack
# ---------------------------------------------------------------------------
log "starting database + wordpress containers"
docker compose up -d db wordpress

log "waiting for database health"
db_ready=0
for _ in $(seq 1 60); do
    if docker compose exec -T db mariadb-admin ping -h localhost -u root -p"${DB_ROOT_PASSWORD}" --silent >/dev/null 2>&1; then
        db_ready=1; break
    fi
    sleep 2
done
[[ "$db_ready" == "1" ]] || die "database did not become healthy within 120s"

# ---------------------------------------------------------------------------
# 4. Install WordPress core (idempotent) and activate Bamero components
# ---------------------------------------------------------------------------
wp() { docker compose --profile tools run --rm wpcli "$@"; }

if wp core is-installed >/dev/null 2>&1; then
    log "WordPress core already installed — skipping core install"
else
    log "installing WordPress core"
    wp core install \
        --url="$DOMAIN" \
        --title="بامرو" \
        --admin_user="$WP_ADMIN_USER" \
        --admin_password="$WP_ADMIN_PASSWORD" \
        --admin_email="$WP_ADMIN_EMAIL" \
        --skip-email
fi

log "activating theme and plugins"
wp theme activate bamero || warn "theme activation reported an issue"
for plugin in \
    bamero-production-core \
    bamero-mobile-auth \
    bamero-zarinpal-gateway \
    bamero-woocommerce-setup \
    bamero-custom-plugin ; do
    wp plugin activate "$plugin" || warn "plugin '$plugin' activation reported an issue"
done

# ---------------------------------------------------------------------------
# 5. Catalog provisioning + rewrite rules
# ---------------------------------------------------------------------------
if [[ -f wp-content/themes/bamero/tools/provision-bamero-catalog.php ]]; then
    log "provisioning Bamero catalog (idempotent by SKU)"
    wp eval-file /var/www/html/wp-content/themes/bamero/tools/provision-bamero-catalog.php --user=1 \
        || warn "catalog provisioning reported an issue"
fi
wp rewrite flush || warn "rewrite flush reported an issue"

log "done. Site: $DOMAIN"
log "health:  $DOMAIN/wp-json/bamero/v1/health/ready"
